#! /usr/bin/env ruby

require 'multi_json'
require 'execjs'
require 'test/unit'

$:.unshift File.dirname(__FILE__)
$:.unshift "#{File.dirname(__FILE__)}/../"

LIB = "#{File.dirname(__FILE__)}/../lib"
VENDOR = "#{File.dirname(__FILE__)}/vendor"
INCLUDES = ["#{File.dirname(__FILE__)}/../src", "#{File.dirname(__FILE__)}/.."]

Dir.glob("#{File.dirname(__FILE__)}/**/*.rb") do |test|
  require test
end

src = File.read("#{LIB}/aurora.js")

Engine = {
  'rubyracer'     => ExecJS::Runtimes::RubyRacer,
  'rubyrhino'     => ExecJS::Runtimes::RubyRhino,
  'johnson'       => ExecJS::Runtimes::Johnson,
  'mustang'       => ExecJS::Runtimes::Mustang,
  'node'          => ExecJS::Runtimes::Node,
  'jsc'           => ExecJS::Runtimes::JavaScriptCore,
  'spidermonkey'  => ExecJS::Runtimes::SpiderMonkey,
  'jscript'       => ExecJS::Runtimes::JScript
}[ENV['AURORA_ENGINE']] || ExecJS::Runtimes::RubyRacer

p Engine

Context = Engine.compile(src)
